name: Download Mesche Compiler
author: David Wilson
description: Downloads a Mesche Compiler build for CI jobs
branding:
  icon: download
  color: yellow
inputs:
  artifact-token:
    description: "The GitHub token to use for artifact download requests.  At a minimum the token will will need 'public:repo' permissions."
    required: true
  os:
    description: "Optional. The target OS of the desired build. Possible values: linux, macos, win-mingw, Defaults to the operating system on which this action is being executed."
    required: false
    default: ""
  arch:
    description: "Optional. The architecture of the desired build (ignored when os = boot). Possible values: x86_64, i686. Defaults to x86_64."
    required: false
    default: "x86_64"
  repo:
    description: "Optional. The repository from which builds will be downloaded. Defaults to mesche-lang/cli."
    required: false
    default: mesche-lang/cli
  workflow-name:
    description: "Optional. The name of the GitHub Actions workflow that produces build artifacts. Defaults to 'Mesche CLI - CI'"
    required: false
    default: "Mesche CLI - CI"
  branch:
    description: "Optional. The branch from which builds will be downloaded. Defaults to master."
    required: false
    default: master
  local-path:
    description: Optional. The local path to which the Mesche build will be unpacked.  Defaults to ./bin.
    required: false
    default: "./bin"
runs:
  using: node16
  main: dist/index.js
