name: Download Mesche - CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./ # Use the action at root of the repo
        with:
          artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

      - name: Run Mesche
        run: mesche

  # NOTE: Linux is the only supported target for now, test the rest once they
  # are supported.

  # Windows:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: ./ # Use the action at root of the repo
  #       with:
  #         os: win-mingw
  #         artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

  #     - name: Run Mesche
  #       run: mesche

  # MacOS:
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: ./ # Use the action at root of the repo
  #       with:
  #         artifact-token: ${{ secrets.ARTIFACT_TOKEN }}

  #     - name: Run Mesche
  #       run: mesche
